/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherLoginRouteImport } from './routes/teacher-login'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTeacherRouteImport } from './routes/dashboard.teacher'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as AcademySlugRouteImport } from './routes/academy.$slug'
import { Route as DashboardTeacherIndexRouteImport } from './routes/dashboard.teacher.index'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard.student.index'
import { Route as DashboardTeacherStudentsRouteImport } from './routes/dashboard.teacher.students'
import { Route as DashboardTeacherResultsRouteImport } from './routes/dashboard.teacher.results'
import { Route as DashboardTeacherQuizzesRouteImport } from './routes/dashboard.teacher.quizzes'
import { Route as DashboardTeacherQuestionBankRouteImport } from './routes/dashboard.teacher.question-bank'
import { Route as DashboardTeacherProfileRouteImport } from './routes/dashboard.teacher.profile'
import { Route as DashboardTeacherMessagesRouteImport } from './routes/dashboard.teacher.messages'
import { Route as DashboardTeacherCoursesRouteImport } from './routes/dashboard.teacher.courses'
import { Route as DashboardTeacherArticlesRouteImport } from './routes/dashboard.teacher.articles'
import { Route as DashboardTeacherAnnouncementsRouteImport } from './routes/dashboard.teacher.announcements'
import { Route as DashboardStudentQuizzesRouteImport } from './routes/dashboard.student.quizzes'
import { Route as DashboardStudentMessagesRouteImport } from './routes/dashboard.student.messages'
import { Route as DashboardStudentCoursesRouteImport } from './routes/dashboard.student.courses'
import { Route as DashboardStudentArticlesRouteImport } from './routes/dashboard.student.articles'
import { Route as AcademySlugLoginRouteImport } from './routes/academy.$slug.login'
import { Route as DashboardTeacherQuizzesIndexRouteImport } from './routes/dashboard.teacher.quizzes.index'
import { Route as DashboardTeacherCoursesIndexRouteImport } from './routes/dashboard.teacher.courses.index'
import { Route as DashboardStudentCoursesIndexRouteImport } from './routes/dashboard.student.courses.index'
import { Route as DashboardTeacherQuizzesNewRouteImport } from './routes/dashboard.teacher.quizzes.new'
import { Route as DashboardTeacherQuizzesQuizIdRouteImport } from './routes/dashboard.teacher.quizzes.$quizId'
import { Route as DashboardTeacherCoursesCourseIdRouteImport } from './routes/dashboard.teacher.courses.$courseId'
import { Route as DashboardStudentResultsAttemptIdRouteImport } from './routes/dashboard.student.results.$attemptId'
import { Route as DashboardStudentQuizQuizIdRouteImport } from './routes/dashboard.student.quiz.$quizId'
import { Route as DashboardStudentCoursesCourseIdRouteImport } from './routes/dashboard.student.courses.$courseId'
import { Route as DashboardStudentAcademyAcademyIdRouteImport } from './routes/dashboard.student.academy.$academyId'
import { Route as DashboardTeacherQuizzesQuizIdResultsRouteImport } from './routes/dashboard.teacher.quizzes.$quizId.results'
import { Route as DashboardStudentResultsAttemptIdReviewRouteImport } from './routes/dashboard.student.results.$attemptId.review'

const TeacherLoginRoute = TeacherLoginRouteImport.update({
  id: '/teacher-login',
  path: '/teacher-login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeacherRoute = DashboardTeacherRouteImport.update({
  id: '/dashboard/teacher',
  path: '/dashboard/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySlugRoute = AcademySlugRouteImport.update({
  id: '/academy/$slug',
  path: '/academy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeacherIndexRoute = DashboardTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardTeacherStudentsRoute =
  DashboardTeacherStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)
const DashboardTeacherResultsRoute = DashboardTeacherResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherQuizzesRoute = DashboardTeacherQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherQuestionBankRoute =
  DashboardTeacherQuestionBankRouteImport.update({
    id: '/question-bank',
    path: '/question-bank',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)
const DashboardTeacherProfileRoute = DashboardTeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherMessagesRoute =
  DashboardTeacherMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)
const DashboardTeacherCoursesRoute = DashboardTeacherCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardTeacherRoute,
} as any)
const DashboardTeacherArticlesRoute =
  DashboardTeacherArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)
const DashboardTeacherAnnouncementsRoute =
  DashboardTeacherAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => DashboardTeacherRoute,
  } as any)
const DashboardStudentQuizzesRoute = DashboardStudentQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentMessagesRoute =
  DashboardStudentMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentCoursesRoute = DashboardStudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentArticlesRoute =
  DashboardStudentArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const AcademySlugLoginRoute = AcademySlugLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AcademySlugRoute,
} as any)
const DashboardTeacherQuizzesIndexRoute =
  DashboardTeacherQuizzesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTeacherQuizzesRoute,
  } as any)
const DashboardTeacherCoursesIndexRoute =
  DashboardTeacherCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTeacherCoursesRoute,
  } as any)
const DashboardStudentCoursesIndexRoute =
  DashboardStudentCoursesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardStudentCoursesRoute,
  } as any)
const DashboardTeacherQuizzesNewRoute =
  DashboardTeacherQuizzesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardTeacherQuizzesRoute,
  } as any)
const DashboardTeacherQuizzesQuizIdRoute =
  DashboardTeacherQuizzesQuizIdRouteImport.update({
    id: '/$quizId',
    path: '/$quizId',
    getParentRoute: () => DashboardTeacherQuizzesRoute,
  } as any)
const DashboardTeacherCoursesCourseIdRoute =
  DashboardTeacherCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => DashboardTeacherCoursesRoute,
  } as any)
const DashboardStudentResultsAttemptIdRoute =
  DashboardStudentResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentQuizQuizIdRoute =
  DashboardStudentQuizQuizIdRouteImport.update({
    id: '/quiz/$quizId',
    path: '/quiz/$quizId',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentCoursesCourseIdRoute =
  DashboardStudentCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => DashboardStudentCoursesRoute,
  } as any)
const DashboardStudentAcademyAcademyIdRoute =
  DashboardStudentAcademyAcademyIdRouteImport.update({
    id: '/academy/$academyId',
    path: '/academy/$academyId',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardTeacherQuizzesQuizIdResultsRoute =
  DashboardTeacherQuizzesQuizIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => DashboardTeacherQuizzesQuizIdRoute,
  } as any)
const DashboardStudentResultsAttemptIdReviewRoute =
  DashboardStudentResultsAttemptIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => DashboardStudentResultsAttemptIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student-login': typeof StudentLoginRoute
  '/teacher-login': typeof TeacherLoginRoute
  '/academy/$slug': typeof AcademySlugRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/dashboard/teacher': typeof DashboardTeacherRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/academy/$slug/login': typeof AcademySlugLoginRoute
  '/dashboard/student/articles': typeof DashboardStudentArticlesRoute
  '/dashboard/student/courses': typeof DashboardStudentCoursesRouteWithChildren
  '/dashboard/student/messages': typeof DashboardStudentMessagesRoute
  '/dashboard/student/quizzes': typeof DashboardStudentQuizzesRoute
  '/dashboard/teacher/announcements': typeof DashboardTeacherAnnouncementsRoute
  '/dashboard/teacher/articles': typeof DashboardTeacherArticlesRoute
  '/dashboard/teacher/courses': typeof DashboardTeacherCoursesRouteWithChildren
  '/dashboard/teacher/messages': typeof DashboardTeacherMessagesRoute
  '/dashboard/teacher/profile': typeof DashboardTeacherProfileRoute
  '/dashboard/teacher/question-bank': typeof DashboardTeacherQuestionBankRoute
  '/dashboard/teacher/quizzes': typeof DashboardTeacherQuizzesRouteWithChildren
  '/dashboard/teacher/results': typeof DashboardTeacherResultsRoute
  '/dashboard/teacher/students': typeof DashboardTeacherStudentsRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/teacher/': typeof DashboardTeacherIndexRoute
  '/dashboard/student/academy/$academyId': typeof DashboardStudentAcademyAcademyIdRoute
  '/dashboard/student/courses/$courseId': typeof DashboardStudentCoursesCourseIdRoute
  '/dashboard/student/quiz/$quizId': typeof DashboardStudentQuizQuizIdRoute
  '/dashboard/student/results/$attemptId': typeof DashboardStudentResultsAttemptIdRouteWithChildren
  '/dashboard/teacher/courses/$courseId': typeof DashboardTeacherCoursesCourseIdRoute
  '/dashboard/teacher/quizzes/$quizId': typeof DashboardTeacherQuizzesQuizIdRouteWithChildren
  '/dashboard/teacher/quizzes/new': typeof DashboardTeacherQuizzesNewRoute
  '/dashboard/student/courses/': typeof DashboardStudentCoursesIndexRoute
  '/dashboard/teacher/courses/': typeof DashboardTeacherCoursesIndexRoute
  '/dashboard/teacher/quizzes/': typeof DashboardTeacherQuizzesIndexRoute
  '/dashboard/student/results/$attemptId/review': typeof DashboardStudentResultsAttemptIdReviewRoute
  '/dashboard/teacher/quizzes/$quizId/results': typeof DashboardTeacherQuizzesQuizIdResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student-login': typeof StudentLoginRoute
  '/teacher-login': typeof TeacherLoginRoute
  '/academy/$slug': typeof AcademySlugRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard': typeof DashboardIndexRoute
  '/academy/$slug/login': typeof AcademySlugLoginRoute
  '/dashboard/student/articles': typeof DashboardStudentArticlesRoute
  '/dashboard/student/messages': typeof DashboardStudentMessagesRoute
  '/dashboard/student/quizzes': typeof DashboardStudentQuizzesRoute
  '/dashboard/teacher/announcements': typeof DashboardTeacherAnnouncementsRoute
  '/dashboard/teacher/articles': typeof DashboardTeacherArticlesRoute
  '/dashboard/teacher/messages': typeof DashboardTeacherMessagesRoute
  '/dashboard/teacher/profile': typeof DashboardTeacherProfileRoute
  '/dashboard/teacher/question-bank': typeof DashboardTeacherQuestionBankRoute
  '/dashboard/teacher/results': typeof DashboardTeacherResultsRoute
  '/dashboard/teacher/students': typeof DashboardTeacherStudentsRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
  '/dashboard/teacher': typeof DashboardTeacherIndexRoute
  '/dashboard/student/academy/$academyId': typeof DashboardStudentAcademyAcademyIdRoute
  '/dashboard/student/courses/$courseId': typeof DashboardStudentCoursesCourseIdRoute
  '/dashboard/student/quiz/$quizId': typeof DashboardStudentQuizQuizIdRoute
  '/dashboard/student/results/$attemptId': typeof DashboardStudentResultsAttemptIdRouteWithChildren
  '/dashboard/teacher/courses/$courseId': typeof DashboardTeacherCoursesCourseIdRoute
  '/dashboard/teacher/quizzes/$quizId': typeof DashboardTeacherQuizzesQuizIdRouteWithChildren
  '/dashboard/teacher/quizzes/new': typeof DashboardTeacherQuizzesNewRoute
  '/dashboard/student/courses': typeof DashboardStudentCoursesIndexRoute
  '/dashboard/teacher/courses': typeof DashboardTeacherCoursesIndexRoute
  '/dashboard/teacher/quizzes': typeof DashboardTeacherQuizzesIndexRoute
  '/dashboard/student/results/$attemptId/review': typeof DashboardStudentResultsAttemptIdReviewRoute
  '/dashboard/teacher/quizzes/$quizId/results': typeof DashboardTeacherQuizzesQuizIdResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student-login': typeof StudentLoginRoute
  '/teacher-login': typeof TeacherLoginRoute
  '/academy/$slug': typeof AcademySlugRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/dashboard/teacher': typeof DashboardTeacherRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/academy/$slug/login': typeof AcademySlugLoginRoute
  '/dashboard/student/articles': typeof DashboardStudentArticlesRoute
  '/dashboard/student/courses': typeof DashboardStudentCoursesRouteWithChildren
  '/dashboard/student/messages': typeof DashboardStudentMessagesRoute
  '/dashboard/student/quizzes': typeof DashboardStudentQuizzesRoute
  '/dashboard/teacher/announcements': typeof DashboardTeacherAnnouncementsRoute
  '/dashboard/teacher/articles': typeof DashboardTeacherArticlesRoute
  '/dashboard/teacher/courses': typeof DashboardTeacherCoursesRouteWithChildren
  '/dashboard/teacher/messages': typeof DashboardTeacherMessagesRoute
  '/dashboard/teacher/profile': typeof DashboardTeacherProfileRoute
  '/dashboard/teacher/question-bank': typeof DashboardTeacherQuestionBankRoute
  '/dashboard/teacher/quizzes': typeof DashboardTeacherQuizzesRouteWithChildren
  '/dashboard/teacher/results': typeof DashboardTeacherResultsRoute
  '/dashboard/teacher/students': typeof DashboardTeacherStudentsRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/teacher/': typeof DashboardTeacherIndexRoute
  '/dashboard/student/academy/$academyId': typeof DashboardStudentAcademyAcademyIdRoute
  '/dashboard/student/courses/$courseId': typeof DashboardStudentCoursesCourseIdRoute
  '/dashboard/student/quiz/$quizId': typeof DashboardStudentQuizQuizIdRoute
  '/dashboard/student/results/$attemptId': typeof DashboardStudentResultsAttemptIdRouteWithChildren
  '/dashboard/teacher/courses/$courseId': typeof DashboardTeacherCoursesCourseIdRoute
  '/dashboard/teacher/quizzes/$quizId': typeof DashboardTeacherQuizzesQuizIdRouteWithChildren
  '/dashboard/teacher/quizzes/new': typeof DashboardTeacherQuizzesNewRoute
  '/dashboard/student/courses/': typeof DashboardStudentCoursesIndexRoute
  '/dashboard/teacher/courses/': typeof DashboardTeacherCoursesIndexRoute
  '/dashboard/teacher/quizzes/': typeof DashboardTeacherQuizzesIndexRoute
  '/dashboard/student/results/$attemptId/review': typeof DashboardStudentResultsAttemptIdReviewRoute
  '/dashboard/teacher/quizzes/$quizId/results': typeof DashboardTeacherQuizzesQuizIdResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/student-login'
    | '/teacher-login'
    | '/academy/$slug'
    | '/dashboard/admin'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/'
    | '/academy/$slug/login'
    | '/dashboard/student/articles'
    | '/dashboard/student/courses'
    | '/dashboard/student/messages'
    | '/dashboard/student/quizzes'
    | '/dashboard/teacher/announcements'
    | '/dashboard/teacher/articles'
    | '/dashboard/teacher/courses'
    | '/dashboard/teacher/messages'
    | '/dashboard/teacher/profile'
    | '/dashboard/teacher/question-bank'
    | '/dashboard/teacher/quizzes'
    | '/dashboard/teacher/results'
    | '/dashboard/teacher/students'
    | '/dashboard/student/'
    | '/dashboard/teacher/'
    | '/dashboard/student/academy/$academyId'
    | '/dashboard/student/courses/$courseId'
    | '/dashboard/student/quiz/$quizId'
    | '/dashboard/student/results/$attemptId'
    | '/dashboard/teacher/courses/$courseId'
    | '/dashboard/teacher/quizzes/$quizId'
    | '/dashboard/teacher/quizzes/new'
    | '/dashboard/student/courses/'
    | '/dashboard/teacher/courses/'
    | '/dashboard/teacher/quizzes/'
    | '/dashboard/student/results/$attemptId/review'
    | '/dashboard/teacher/quizzes/$quizId/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/student-login'
    | '/teacher-login'
    | '/academy/$slug'
    | '/dashboard/admin'
    | '/dashboard'
    | '/academy/$slug/login'
    | '/dashboard/student/articles'
    | '/dashboard/student/messages'
    | '/dashboard/student/quizzes'
    | '/dashboard/teacher/announcements'
    | '/dashboard/teacher/articles'
    | '/dashboard/teacher/messages'
    | '/dashboard/teacher/profile'
    | '/dashboard/teacher/question-bank'
    | '/dashboard/teacher/results'
    | '/dashboard/teacher/students'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/student/academy/$academyId'
    | '/dashboard/student/courses/$courseId'
    | '/dashboard/student/quiz/$quizId'
    | '/dashboard/student/results/$attemptId'
    | '/dashboard/teacher/courses/$courseId'
    | '/dashboard/teacher/quizzes/$quizId'
    | '/dashboard/teacher/quizzes/new'
    | '/dashboard/student/courses'
    | '/dashboard/teacher/courses'
    | '/dashboard/teacher/quizzes'
    | '/dashboard/student/results/$attemptId/review'
    | '/dashboard/teacher/quizzes/$quizId/results'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/reset-password'
    | '/student-login'
    | '/teacher-login'
    | '/academy/$slug'
    | '/dashboard/admin'
    | '/dashboard/student'
    | '/dashboard/teacher'
    | '/dashboard/'
    | '/academy/$slug/login'
    | '/dashboard/student/articles'
    | '/dashboard/student/courses'
    | '/dashboard/student/messages'
    | '/dashboard/student/quizzes'
    | '/dashboard/teacher/announcements'
    | '/dashboard/teacher/articles'
    | '/dashboard/teacher/courses'
    | '/dashboard/teacher/messages'
    | '/dashboard/teacher/profile'
    | '/dashboard/teacher/question-bank'
    | '/dashboard/teacher/quizzes'
    | '/dashboard/teacher/results'
    | '/dashboard/teacher/students'
    | '/dashboard/student/'
    | '/dashboard/teacher/'
    | '/dashboard/student/academy/$academyId'
    | '/dashboard/student/courses/$courseId'
    | '/dashboard/student/quiz/$quizId'
    | '/dashboard/student/results/$attemptId'
    | '/dashboard/teacher/courses/$courseId'
    | '/dashboard/teacher/quizzes/$quizId'
    | '/dashboard/teacher/quizzes/new'
    | '/dashboard/student/courses/'
    | '/dashboard/teacher/courses/'
    | '/dashboard/teacher/quizzes/'
    | '/dashboard/student/results/$attemptId/review'
    | '/dashboard/teacher/quizzes/$quizId/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StudentLoginRoute: typeof StudentLoginRoute
  TeacherLoginRoute: typeof TeacherLoginRoute
  AcademySlugRoute: typeof AcademySlugRouteWithChildren
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardStudentRoute: typeof DashboardStudentRouteWithChildren
  DashboardTeacherRoute: typeof DashboardTeacherRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher-login': {
      id: '/teacher-login'
      path: '/teacher-login'
      fullPath: '/teacher-login'
      preLoaderRoute: typeof TeacherLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-login': {
      id: '/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teacher': {
      id: '/dashboard/teacher'
      path: '/dashboard/teacher'
      fullPath: '/dashboard/teacher'
      preLoaderRoute: typeof DashboardTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$slug': {
      id: '/academy/$slug'
      path: '/academy/$slug'
      fullPath: '/academy/$slug'
      preLoaderRoute: typeof AcademySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/teacher/': {
      id: '/dashboard/teacher/'
      path: '/'
      fullPath: '/dashboard/teacher/'
      preLoaderRoute: typeof DashboardTeacherIndexRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/teacher/students': {
      id: '/dashboard/teacher/students'
      path: '/students'
      fullPath: '/dashboard/teacher/students'
      preLoaderRoute: typeof DashboardTeacherStudentsRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/results': {
      id: '/dashboard/teacher/results'
      path: '/results'
      fullPath: '/dashboard/teacher/results'
      preLoaderRoute: typeof DashboardTeacherResultsRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/quizzes': {
      id: '/dashboard/teacher/quizzes'
      path: '/quizzes'
      fullPath: '/dashboard/teacher/quizzes'
      preLoaderRoute: typeof DashboardTeacherQuizzesRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/question-bank': {
      id: '/dashboard/teacher/question-bank'
      path: '/question-bank'
      fullPath: '/dashboard/teacher/question-bank'
      preLoaderRoute: typeof DashboardTeacherQuestionBankRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/profile': {
      id: '/dashboard/teacher/profile'
      path: '/profile'
      fullPath: '/dashboard/teacher/profile'
      preLoaderRoute: typeof DashboardTeacherProfileRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/messages': {
      id: '/dashboard/teacher/messages'
      path: '/messages'
      fullPath: '/dashboard/teacher/messages'
      preLoaderRoute: typeof DashboardTeacherMessagesRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/courses': {
      id: '/dashboard/teacher/courses'
      path: '/courses'
      fullPath: '/dashboard/teacher/courses'
      preLoaderRoute: typeof DashboardTeacherCoursesRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/articles': {
      id: '/dashboard/teacher/articles'
      path: '/articles'
      fullPath: '/dashboard/teacher/articles'
      preLoaderRoute: typeof DashboardTeacherArticlesRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/teacher/announcements': {
      id: '/dashboard/teacher/announcements'
      path: '/announcements'
      fullPath: '/dashboard/teacher/announcements'
      preLoaderRoute: typeof DashboardTeacherAnnouncementsRouteImport
      parentRoute: typeof DashboardTeacherRoute
    }
    '/dashboard/student/quizzes': {
      id: '/dashboard/student/quizzes'
      path: '/quizzes'
      fullPath: '/dashboard/student/quizzes'
      preLoaderRoute: typeof DashboardStudentQuizzesRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/messages': {
      id: '/dashboard/student/messages'
      path: '/messages'
      fullPath: '/dashboard/student/messages'
      preLoaderRoute: typeof DashboardStudentMessagesRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/courses': {
      id: '/dashboard/student/courses'
      path: '/courses'
      fullPath: '/dashboard/student/courses'
      preLoaderRoute: typeof DashboardStudentCoursesRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/articles': {
      id: '/dashboard/student/articles'
      path: '/articles'
      fullPath: '/dashboard/student/articles'
      preLoaderRoute: typeof DashboardStudentArticlesRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/academy/$slug/login': {
      id: '/academy/$slug/login'
      path: '/login'
      fullPath: '/academy/$slug/login'
      preLoaderRoute: typeof AcademySlugLoginRouteImport
      parentRoute: typeof AcademySlugRoute
    }
    '/dashboard/teacher/quizzes/': {
      id: '/dashboard/teacher/quizzes/'
      path: '/'
      fullPath: '/dashboard/teacher/quizzes/'
      preLoaderRoute: typeof DashboardTeacherQuizzesIndexRouteImport
      parentRoute: typeof DashboardTeacherQuizzesRoute
    }
    '/dashboard/teacher/courses/': {
      id: '/dashboard/teacher/courses/'
      path: '/'
      fullPath: '/dashboard/teacher/courses/'
      preLoaderRoute: typeof DashboardTeacherCoursesIndexRouteImport
      parentRoute: typeof DashboardTeacherCoursesRoute
    }
    '/dashboard/student/courses/': {
      id: '/dashboard/student/courses/'
      path: '/'
      fullPath: '/dashboard/student/courses/'
      preLoaderRoute: typeof DashboardStudentCoursesIndexRouteImport
      parentRoute: typeof DashboardStudentCoursesRoute
    }
    '/dashboard/teacher/quizzes/new': {
      id: '/dashboard/teacher/quizzes/new'
      path: '/new'
      fullPath: '/dashboard/teacher/quizzes/new'
      preLoaderRoute: typeof DashboardTeacherQuizzesNewRouteImport
      parentRoute: typeof DashboardTeacherQuizzesRoute
    }
    '/dashboard/teacher/quizzes/$quizId': {
      id: '/dashboard/teacher/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/dashboard/teacher/quizzes/$quizId'
      preLoaderRoute: typeof DashboardTeacherQuizzesQuizIdRouteImport
      parentRoute: typeof DashboardTeacherQuizzesRoute
    }
    '/dashboard/teacher/courses/$courseId': {
      id: '/dashboard/teacher/courses/$courseId'
      path: '/$courseId'
      fullPath: '/dashboard/teacher/courses/$courseId'
      preLoaderRoute: typeof DashboardTeacherCoursesCourseIdRouteImport
      parentRoute: typeof DashboardTeacherCoursesRoute
    }
    '/dashboard/student/results/$attemptId': {
      id: '/dashboard/student/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/dashboard/student/results/$attemptId'
      preLoaderRoute: typeof DashboardStudentResultsAttemptIdRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/quiz/$quizId': {
      id: '/dashboard/student/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/dashboard/student/quiz/$quizId'
      preLoaderRoute: typeof DashboardStudentQuizQuizIdRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/courses/$courseId': {
      id: '/dashboard/student/courses/$courseId'
      path: '/$courseId'
      fullPath: '/dashboard/student/courses/$courseId'
      preLoaderRoute: typeof DashboardStudentCoursesCourseIdRouteImport
      parentRoute: typeof DashboardStudentCoursesRoute
    }
    '/dashboard/student/academy/$academyId': {
      id: '/dashboard/student/academy/$academyId'
      path: '/academy/$academyId'
      fullPath: '/dashboard/student/academy/$academyId'
      preLoaderRoute: typeof DashboardStudentAcademyAcademyIdRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/teacher/quizzes/$quizId/results': {
      id: '/dashboard/teacher/quizzes/$quizId/results'
      path: '/results'
      fullPath: '/dashboard/teacher/quizzes/$quizId/results'
      preLoaderRoute: typeof DashboardTeacherQuizzesQuizIdResultsRouteImport
      parentRoute: typeof DashboardTeacherQuizzesQuizIdRoute
    }
    '/dashboard/student/results/$attemptId/review': {
      id: '/dashboard/student/results/$attemptId/review'
      path: '/review'
      fullPath: '/dashboard/student/results/$attemptId/review'
      preLoaderRoute: typeof DashboardStudentResultsAttemptIdReviewRouteImport
      parentRoute: typeof DashboardStudentResultsAttemptIdRoute
    }
  }
}

interface AcademySlugRouteChildren {
  AcademySlugLoginRoute: typeof AcademySlugLoginRoute
}

const AcademySlugRouteChildren: AcademySlugRouteChildren = {
  AcademySlugLoginRoute: AcademySlugLoginRoute,
}

const AcademySlugRouteWithChildren = AcademySlugRoute._addFileChildren(
  AcademySlugRouteChildren,
)

interface DashboardStudentCoursesRouteChildren {
  DashboardStudentCoursesCourseIdRoute: typeof DashboardStudentCoursesCourseIdRoute
  DashboardStudentCoursesIndexRoute: typeof DashboardStudentCoursesIndexRoute
}

const DashboardStudentCoursesRouteChildren: DashboardStudentCoursesRouteChildren =
  {
    DashboardStudentCoursesCourseIdRoute: DashboardStudentCoursesCourseIdRoute,
    DashboardStudentCoursesIndexRoute: DashboardStudentCoursesIndexRoute,
  }

const DashboardStudentCoursesRouteWithChildren =
  DashboardStudentCoursesRoute._addFileChildren(
    DashboardStudentCoursesRouteChildren,
  )

interface DashboardStudentResultsAttemptIdRouteChildren {
  DashboardStudentResultsAttemptIdReviewRoute: typeof DashboardStudentResultsAttemptIdReviewRoute
}

const DashboardStudentResultsAttemptIdRouteChildren: DashboardStudentResultsAttemptIdRouteChildren =
  {
    DashboardStudentResultsAttemptIdReviewRoute:
      DashboardStudentResultsAttemptIdReviewRoute,
  }

const DashboardStudentResultsAttemptIdRouteWithChildren =
  DashboardStudentResultsAttemptIdRoute._addFileChildren(
    DashboardStudentResultsAttemptIdRouteChildren,
  )

interface DashboardStudentRouteChildren {
  DashboardStudentArticlesRoute: typeof DashboardStudentArticlesRoute
  DashboardStudentCoursesRoute: typeof DashboardStudentCoursesRouteWithChildren
  DashboardStudentMessagesRoute: typeof DashboardStudentMessagesRoute
  DashboardStudentQuizzesRoute: typeof DashboardStudentQuizzesRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
  DashboardStudentAcademyAcademyIdRoute: typeof DashboardStudentAcademyAcademyIdRoute
  DashboardStudentQuizQuizIdRoute: typeof DashboardStudentQuizQuizIdRoute
  DashboardStudentResultsAttemptIdRoute: typeof DashboardStudentResultsAttemptIdRouteWithChildren
}

const DashboardStudentRouteChildren: DashboardStudentRouteChildren = {
  DashboardStudentArticlesRoute: DashboardStudentArticlesRoute,
  DashboardStudentCoursesRoute: DashboardStudentCoursesRouteWithChildren,
  DashboardStudentMessagesRoute: DashboardStudentMessagesRoute,
  DashboardStudentQuizzesRoute: DashboardStudentQuizzesRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
  DashboardStudentAcademyAcademyIdRoute: DashboardStudentAcademyAcademyIdRoute,
  DashboardStudentQuizQuizIdRoute: DashboardStudentQuizQuizIdRoute,
  DashboardStudentResultsAttemptIdRoute:
    DashboardStudentResultsAttemptIdRouteWithChildren,
}

const DashboardStudentRouteWithChildren =
  DashboardStudentRoute._addFileChildren(DashboardStudentRouteChildren)

interface DashboardTeacherCoursesRouteChildren {
  DashboardTeacherCoursesCourseIdRoute: typeof DashboardTeacherCoursesCourseIdRoute
  DashboardTeacherCoursesIndexRoute: typeof DashboardTeacherCoursesIndexRoute
}

const DashboardTeacherCoursesRouteChildren: DashboardTeacherCoursesRouteChildren =
  {
    DashboardTeacherCoursesCourseIdRoute: DashboardTeacherCoursesCourseIdRoute,
    DashboardTeacherCoursesIndexRoute: DashboardTeacherCoursesIndexRoute,
  }

const DashboardTeacherCoursesRouteWithChildren =
  DashboardTeacherCoursesRoute._addFileChildren(
    DashboardTeacherCoursesRouteChildren,
  )

interface DashboardTeacherQuizzesQuizIdRouteChildren {
  DashboardTeacherQuizzesQuizIdResultsRoute: typeof DashboardTeacherQuizzesQuizIdResultsRoute
}

const DashboardTeacherQuizzesQuizIdRouteChildren: DashboardTeacherQuizzesQuizIdRouteChildren =
  {
    DashboardTeacherQuizzesQuizIdResultsRoute:
      DashboardTeacherQuizzesQuizIdResultsRoute,
  }

const DashboardTeacherQuizzesQuizIdRouteWithChildren =
  DashboardTeacherQuizzesQuizIdRoute._addFileChildren(
    DashboardTeacherQuizzesQuizIdRouteChildren,
  )

interface DashboardTeacherQuizzesRouteChildren {
  DashboardTeacherQuizzesQuizIdRoute: typeof DashboardTeacherQuizzesQuizIdRouteWithChildren
  DashboardTeacherQuizzesNewRoute: typeof DashboardTeacherQuizzesNewRoute
  DashboardTeacherQuizzesIndexRoute: typeof DashboardTeacherQuizzesIndexRoute
}

const DashboardTeacherQuizzesRouteChildren: DashboardTeacherQuizzesRouteChildren =
  {
    DashboardTeacherQuizzesQuizIdRoute:
      DashboardTeacherQuizzesQuizIdRouteWithChildren,
    DashboardTeacherQuizzesNewRoute: DashboardTeacherQuizzesNewRoute,
    DashboardTeacherQuizzesIndexRoute: DashboardTeacherQuizzesIndexRoute,
  }

const DashboardTeacherQuizzesRouteWithChildren =
  DashboardTeacherQuizzesRoute._addFileChildren(
    DashboardTeacherQuizzesRouteChildren,
  )

interface DashboardTeacherRouteChildren {
  DashboardTeacherAnnouncementsRoute: typeof DashboardTeacherAnnouncementsRoute
  DashboardTeacherArticlesRoute: typeof DashboardTeacherArticlesRoute
  DashboardTeacherCoursesRoute: typeof DashboardTeacherCoursesRouteWithChildren
  DashboardTeacherMessagesRoute: typeof DashboardTeacherMessagesRoute
  DashboardTeacherProfileRoute: typeof DashboardTeacherProfileRoute
  DashboardTeacherQuestionBankRoute: typeof DashboardTeacherQuestionBankRoute
  DashboardTeacherQuizzesRoute: typeof DashboardTeacherQuizzesRouteWithChildren
  DashboardTeacherResultsRoute: typeof DashboardTeacherResultsRoute
  DashboardTeacherStudentsRoute: typeof DashboardTeacherStudentsRoute
  DashboardTeacherIndexRoute: typeof DashboardTeacherIndexRoute
}

const DashboardTeacherRouteChildren: DashboardTeacherRouteChildren = {
  DashboardTeacherAnnouncementsRoute: DashboardTeacherAnnouncementsRoute,
  DashboardTeacherArticlesRoute: DashboardTeacherArticlesRoute,
  DashboardTeacherCoursesRoute: DashboardTeacherCoursesRouteWithChildren,
  DashboardTeacherMessagesRoute: DashboardTeacherMessagesRoute,
  DashboardTeacherProfileRoute: DashboardTeacherProfileRoute,
  DashboardTeacherQuestionBankRoute: DashboardTeacherQuestionBankRoute,
  DashboardTeacherQuizzesRoute: DashboardTeacherQuizzesRouteWithChildren,
  DashboardTeacherResultsRoute: DashboardTeacherResultsRoute,
  DashboardTeacherStudentsRoute: DashboardTeacherStudentsRoute,
  DashboardTeacherIndexRoute: DashboardTeacherIndexRoute,
}

const DashboardTeacherRouteWithChildren =
  DashboardTeacherRoute._addFileChildren(DashboardTeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StudentLoginRoute: StudentLoginRoute,
  TeacherLoginRoute: TeacherLoginRoute,
  AcademySlugRoute: AcademySlugRouteWithChildren,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardStudentRoute: DashboardStudentRouteWithChildren,
  DashboardTeacherRoute: DashboardTeacherRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
